#index:
#    path: /
#    controller: App\Controller\DefaultController::index
    
api_graphql_entrypoint:
    path: /graphql
    controller: api_platform.graphql.action.entrypoint

token_authentication:
    path: /token/authentication
    methods: ['POST']
